# Generated by Django 2.2.5 on 2020-02-18 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200218_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='The student number should be in correct format. e.g.(2015-02986-MN-0)', regex='^(199\\d|200\\d|2020)-(\x08\\d{5}\x08)-(MN|mn)-(0|1)$')]),
        ),
    ]
